version: '2'

services:
   robot-framework-target:
     image: playniuniu/robot-framework-target
     volumes:
       - ~/vol/robot/robot_target:/opt/web/
     ports:
       - 8000:80

   robot-framework:
     depends_on:
       - robot-framework-target
     image: playniuniu/robot-framework
     environment:
       DISPLAY: unix$DISPLAY
     volumes:
       - /tmp/.X11-unix:/tmp/.X11-unix
       - ~/vol/robot/robot_testcases:/testcases

